# Generated by Django 2.0.1 on 2018-01-17 23:03

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('nutrition_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='nutrition value')),
                ('picture', models.ImageField(upload_to=core.models.image_file_name_generator, verbose_name='picture')),
            ],
        ),
    ]
